<a href="https://colab.research.google.com/github/Sanju094/ML1/blob/main/Tensorflow(mnist).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist
mnist

<module 'keras.api._v2.keras.datasets.mnist' from '/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
# Building a model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.11615992, -0.6820611 ,  0.01731861, -0.52692   ,  0.4081873 ,
         0.08239071, -0.5232961 ,  0.13973579, -0.02318113,  0.28314477]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.11375628, 0.05120501, 0.10305028, 0.05979837, 0.15233555,
        0.10997896, 0.06001547, 0.11647005, 0.09896015, 0.13442995]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.2074661

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2999 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1455 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1089 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0874 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0747 - accuracy: 0.9769


In [ ]:
# calculating accuracy
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0819 - accuracy: 0.9752 - 320ms/epoch - 1ms/step


[0.081927090883255, 0.9751999974250793]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.02121976e-06, 1.43709311e-09, 1.87350979e-05, 2.93625490e-04,
        9.82577977e-11, 9.45061274e-09, 2.14305190e-13, 9.99641418e-01,
        3.20015317e-07, 4.48137398e-05],
       [6.92756241e-10, 8.52130121e-04, 9.99056876e-01, 8.99530642e-05,
        3.22165390e-13, 3.15621037e-07, 2.49203502e-08, 9.05268861e-13,
        7.67350116e-07, 1.44070979e-11],
       [3.08092297e-07, 9.98993456e-01, 6.94947303e-05, 1.52639859e-05,
        2.18679033e-05, 1.24765722e-06, 1.32445803e-05, 4.88707330e-04,
        3.96249874e-04, 1.72084185e-07],
       [9.99981880e-01, 8.50886972e-10, 3.14270915e-06, 2.98308294e-08,
        5.91814739e-08, 4.36733174e-08, 1.03049397e-05, 4.26805582e-06,
        1.07629454e-10, 3.98130680e-07],
       [8.89749208e-06, 1.05956680e-07, 1.17830132e-05, 6.92923479e-08,
        9.98885334e-01, 1.55934401e-07, 9.20434289e-08, 8.41296496e-05,
        1.41079011e-06, 1.00803433e-03]], dtype=float32)>